name: Java CI

on:
  push:
    branches:
    - feature/sampleGithub

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run java program
        run: java -cp target/classes/Main

      - name: Run tests
        run: mvn test
